name: Build project
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: 'hl2sdk-starter'
          submodules: 'recursive'
      - name: Install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install gcc gcc-multilib g++ g++-multilib
          python3 python3-pip python3-setuptools python3-wheel ninja-build &&
          pip3 install --user meson
      - name: Build
        run: >
          cd ${{ github.workspace }}/hl2sdk-starter &&
          ./build-matrix.sh
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries_${{github.sha}}
          path: ${{ github.workspace }}/hl2sdk-starter/bin/*.so

